routes/web.php
<?php

Route::get('/', 'HomeController@index');

Route::get('/admin', function(){
    
    return view('admin');
})->middleware('auth');

Route::get('/home','HomeController@index');


Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');
});



Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {



});
Route::get('admin/cards', 'CardController@index')->name('admin.cards');

Route::get('/admin/card/create','CardController@create');

Route::post('/admin/card/store','CardController@store');

Route::get('/admin/card/{id}/edit','CardController@edit');

Route::put('/admin/card/{id}/update','CardController@update');

Route::delete('/admin/card/{id}/delete','CardController@destroy');

Route::get('/admin/product','ProductController@index');


Route::get('admin/categories', 'CategoryController@index')->name('admin.categories');


Route::get('/admin/category/create','CategoryController@create');

Route::post('/admin/category/store','CategoryController@store');

Route::get('/admin/category/{id}/edit','CategoryController@edit');

Route::put('/admin/category/{id}/update','CategoryController@update');

Route::delete('/admin/category/{id}/delete','CategoryController@destroy');

Route::get('/product','CardController@getCardProducts');

// Route::get('/getCardProducts','CardController@getCardProducts');

Route::get('/getByCategory/{id}','CardController@getByCategory');




Route::get('/admin/bcc','BccController@index');

Route::get('/admin/bcc/create','BccController@create');

Route::post('/admin/bcc/store','BccController@store');

Route::get('/admin/bcc/{id}/edit','BccController@edit');

Route::put('/admin/bcc/{id}/update','BccController@update');

Route::delete('/admin/bcc/{id}/delete','BccController@destroy');






Route::get('/admin/top_slider','Top_sliderController@index');

Route::post('/admin/top_slider/store','Top_sliderController@store');

Route::put('/admin/top_slider/{id}/update','Top_sliderController@update');

Route::delete('/admin/top_slider/{id}/delete','Top_sliderController@destroy');




Route::get('/admin/mid_slider','Mid_sliderController@index');

Route::post('/admin/mid_slider/store','Mid_sliderController@store');

Route::put('/admin/mid_slider/{id}/update','Mid_sliderController@update');

Route::delete('/admin/mid_slider/{id}/delete','Mid_sliderController@destroy');



Route::get('/admin/last_slider','Last_sliderController@index');

Route::post('/admin/last_slider/store','Last_sliderController@store');

Route::put('/admin/last_slider/{id}/update','Last_sliderController@update');

Route::delete('/admin/last_slider/{id}/delete','Last_sliderController@destroy');





Route::get('/admin/paypal','PaypalController@index');

Route::post('/sendPaypal','PaypalController@store');

Route::delete('admin/paypal/{id}/delete','PaypalController@destroy');





Route::get('/sales',function(){
    return view('sales');    
});
Route::get('/payment/{cost}','PaymentController@show')->name('payment');

Route::get('/payment',function(){
    return view('payment',[
        "cost"=>NULL
    ]);    
});

Route::get('/admin/payment','PaymentController@index');

Route::post('/payment','PaymentController@store');

Route::delete('/admin/payment/{id}/delete','PaymentController@destroy');

Route::get('/sendMail','PaypalController@sendMail');



Route::get('/install', function(){
    echo exec("pwd");
    echo exec("cd ../ && php artisan key:generate");
    echo exec("cd ../ && php artisan migrate --seed");

    echo exec("php artisan key:generate");
    echo exec("php artisan migrate --seed");
});







Route::get('/admin/contact','ContactController@index');

Route::post('/contact','ContactController@store')->name('contact');

Route::delete('/admin/contact/{id}/delete','ContactController@destroy');

Route::get('/opportunity',function(){
    return view('opportunity');
});

Route::get('/sendthis','PaymentController@sendthis');

Route::get('/test','PdfController@test');

resources/views/partials/footer.blade.php
<footer class="bottom-footer">
    <div class="usefull">
        <h1>USEFUL LINKS</h1>
        <p><a href="{{ url('/home') }}">Home</a></p>
        <p><a href="{{ url('/product') }}">Products</a></p>
        <p><a href="{{ url('/sales') }}">Sales</a></p>
        <p><a href="{{ url('/payment') }}">Payment</a></p>
        <p><a href="http://bccagents.biz/">BCC Opportunities</a></p>

    </div>
    <div class="usefull">
        <h1>SOCIAL MEDIA</h1>
        <p><a href="#"><i class="fab fa-facebook-square"></i> Facebook</a></p>
        <p><a href="#"><i class="fab fa-twitter"></i> Twitter</a></p>
        <p><a href="#"><i class="fab fa-youtube"></i> YouTube</a></p>
        <p><a href="#"><i class="fab fa-google"></i> Google+</a></p>
    </div>
    <div class="usefull">
        <h1>PAYMENTS</h1>
        <div style="width:200px;"><img src="/images/Imagesss/img/paypal-logo.png" style="width:100%;height:100%;"></div>
    </div>
</footer>
<footer class="bead-bottom">
    <div>© 2020 Bank Coin Credit. All Rights Reserved.</div>
    <div class="u-rigrex"><a href="https://rigrex.com/" target="_blank">Developed by :<img src="/images/Imagesss/img/rigrex.png" class="rigrex"> RigRex | Creators Of Tomorrow</a><div>
<footer>

resources/views/partials/menu.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="min-height: 917px;">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="/images/sales/logo.jpg" class="admin-logo">
        <span class="brand-text font-weight-light">ADMIN PANEL</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{ url("admin") }}" class="nav-link {{ request()->is('admin') ? 'active' : '' }}">
                        <i class="fas fa-tachometer-alt"></i>
                        <p>
                            <span>{{ trans('global.dashboard') }}</span>
                        </p>
                    </a>
                </li>
                {{-- @can('user_management_access') --}}

                <li class="nav-item">
                    <a href="{{ url("/admin/paypal") }}" class="nav-link {{ request()->is('admin/paypal') || request()->is('admin/paypal/*') ? 'active' : '' }}">
                        <i class="fab fa-cc-paypal"></i>
                        <p>
                            <span>Paypal Record</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url("/admin/payment") }}" class="nav-link {{ request()->is('admin/payment') || request()->is('admin/payment/*') ? 'active' : '' }}">
                        <i class="fas fa-paragraph"></i>
                        <p>
                            <span>Payment Record</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url("/admin/contact") }}" class="nav-link {{ request()->is('admin/contact') || request()->is('admin/contact/*') ? 'active' : '' }}">
                        <i class="fas fa-file-signature"></i>
                        <p>
                            <span>Contact Messages</span>
                        </p>
                    </a>
                </li>
                    {{-- <li class="nav-item has-treeview {{ request()->is('admin/permissions*') ? 'menu-open' : '' }} {{ request()->is('admin/roles*') ? 'menu-open' : '' }} {{ request()->is('admin/users*') ? 'menu-open' : '' }}">
                        <a class="nav-link nav-dropdown-toggle">
                            <i class="fas fa-users">

                            </i>
                            <p>
                                <span>{{ trans('global.userManagement.title') }}</span>
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            @can('permission_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                                        <i class="fas fa-unlock-alt">

                                        </i>
                                        <p>
                                            <span>{{ trans('global.permission.title') }}</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                            @can('role_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                        <i class="fas fa-briefcase">

                                        </i>
                                        <p>
                                            <span>{{ trans('global.role.title') }}</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                            @can('user_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                        <i class="fas fa-user">

                                        </i>
                                        <p>
                                            <span>{{ trans('global.user.title') }}</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                        </ul>
                    </li>
                @endcan
                @can('product_access')
                    <li class="nav-item">
                        <a href="{{ route("admin.products.index") }}" class="nav-link {{ request()->is('admin/products') || request()->is('admin/products/*') ? 'active' : '' }}">
                            <i class="fas fa-cogs">

                            </i>
                            <p>
                                <span>{{ trans('global.product.title') }}</span>
                            </p>
                        </a>
                    </li>
                @endcan --}}

                {{-- *************************************************** items toggle ******************************************* --}}
                <li class="nav-item has-treeview {{ request()->is('admin/cards*') ? 'menu-open' : '' }} {{ request()->is('admin/categories*') ? 'menu-open' : '' }}" style="cursor:pointer">
                    <a class="nav-link nav-dropdown-toggle">
                        <i class="fab fa-product-hunt"></i>
                        <p>
                            <span> Products </span>
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>
                        <ul class="nav nav-treeview">
                            @can('permission_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.cards") }}" class="nav-link {{ request()->is('admin/cards') || request()->is('admin/cards/*') ? 'active' : '' }}">
                                        <i class="far fa-credit-card"></i>
                                        <p>
                                            <span>cards</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                            @can('role_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.categories") }}" class="nav-link {{ request()->is('admin/categories') || request()->is('admin/categories/*') ? 'active' : '' }}">
                                        <i class="fab fa-cuttlefish"></i>
                                        <p>
                                            <span>categories</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                            
                        </ul>
                </li>
                {{-- <li class="nav-item">
                    <a href="{{ url("/admin/product") }}" class="nav-link {{ request()->is('admin/product') || request()->is('admin/product/*') ? 'active' : '' }}">
                        <p>
                            <i class="fab fa-product-hunt"></i>
                            <span>products</span>
                        </p>
                    </a>
                </li> --}}
                <li class="nav-item">
                    <a href="{{ url("/admin/bcc") }}" class="nav-link {{ request()->is('admin/bcc') || request()->is('admin/bcc/*') ? 'active' : '' }}">
                        <i class="fas fa-bold"></i>
                        <p>
                            <span>BCC sliders</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url("/admin/top_slider") }}" class="nav-link {{ request()->is('admin/top_slider') || request()->is('admin/top_slider/*') ? 'active' : '' }}">
                        <i class="fas fa-long-arrow-alt-up"></i>
                        <p>
                            <span>top slider</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url("/admin/mid_slider") }}" class="nav-link {{ request()->is('admin/mid_slider') || request()->is('admin/mid_slider/*') ? 'active' : '' }}">
                        <i class="fas fa-long-arrow-alt-right"></i>
                        <p>
                            <span>mid slider</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url("/admin/last_slider") }}" class="nav-link {{ request()->is('admin/last_slider') || request()->is('admin/last_slider/*') ? 'active' : '' }}">
                        <i class="fas fa-long-arrow-alt-down"></i>
                        <p>
                            <span>last slider</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                        <i class="fas fa-sign-out-alt"></i>
                        <p>
                            <span>{{ trans('global.logout') }}</span>
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/partials/partner.blade.php
{{-- <link rel="stylesheet" href="./css/bootstrap.min.css" />
    <!-- Magnific Popup core CSS file -->
    <link rel="stylesheet" href="../css/magnific-popup.css" /> --}}
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="/css/owl.theme.default.min.css" />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,600,700&amp;display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:100,200,300,400,600,700&amp;display=swap"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <!-- Main css -->
    <link rel="stylesheet" href="/css/main.css" />

resources/views/partials/site_nav.blade.php
{{-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
                @if (Route::has('login'))
                    @auth
                        <li class="nav-item active">
                            <a href="{{ url('/home') }}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a href="{{ url('/product') }}" class="nav-link">products</a>
                        </li>
                        <li class="nav-item active">
                            <a href="{{ url('/sales') }}" class="nav-link">sales</a>
                        </li>
                        <li class="nav-item active">
                            <a href="{{ url('/payment') }}" class="nav-link">payment</a>
                        </li>
                        <li class="nav-item active">
                            <a href="{{ url('/logout') }}" class="nav-link">logout</a>
                        </li>
                    @else
                        <li class="nav-item active">
                            <a href="{{ route('login') }}" class="nav-link">Login</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item active">
                                <a href="{{ route('register') }}" class="nav-link">Register</a>
                            </li>
                        @endif
                    @endauth
            @endif
    </ul>
  </div>
</nav> --}}

<nav class="nav-inactive nav-color" >
    <div class="logo">
        {{-- <h4>LOGO</h4> --}}
        <div class="img-con">
            <img src="/images/sales/logo.jpg">
        </div>
    </div>
    <ul class="nav-links">
        <li>
            <a href="{{ url('/home') }}">Home</a>
        </li>
        <li>
            <a href="{{ url('/product') }}">Products</a>
        </li>
        <li>
            <a href="{{ url('/sales') }}">Sales</a>
        </li>
        <li>
            <a href="{{ url('/payment') }}">Payments</a>
        </li>
         <li>
            <a href="http://bccagents.biz/">BCC Opportunities</a>
        </li>
    </ul>
    <div class="email" >
        <h5><i class="far fa-envelope meMail"></i>bankcoincredit@gmail.com</h5>
    </div>
    <div class="burger">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
    </div>
</nav>